name: Run pr checks when a PR is opened
on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - 'packages/core-ui-kit/**'
      - 'package.json'

jobs:
  run-checks:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Run Lint
        env:
          CI: true
          NODE_OPTIONS: '--max_old_space_size=4096'
        run: pnpm lint
      - name: Run Test
        env:
          CI: true
          NODE_OPTIONS: '--max_old_space_size=4096'
        run: pnpm test
      - name: Run Build
        env:
          CI: true
          NODE_OPTIONS: '--max_old_space_size=4096'
        run: pnpm build
