name: Run pr checks when a PR is opened
on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - 'packages/core-ui-kit/**'
      - 'package.json'

jobs:
  run-checks:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Run Checks
        env:
          CI: true
        run: pnpx nx lint core-ui-kit && pnpx nx test core-ui-kit && pnpx nx build core-ui-kit
